// export const DELETE='DELETE'
// export const EDIT='EDIT'
// export const UPDATE='UPDATE'
export const LOGIN='LOGIN'
export const SETPROFILE='SETPROFILE'
export const DELETESTATE='DELETESTATE'
export const SETWEBSOCKETSTATE='SETWEBSOCKETSTATE'
export const MENUITEM='MENUITEM'
export const CHANGETHEME='CHANGETHEME'

